name: Ubuntu 18.04 CI
on: [push, pull_request]

jobs:
  build-and-open:
    runs-on: ubuntu-18.04
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.6.1'

      - uses: r-lib/actions/setup-pandoc@master
      - name: Install Ubuntu deps
        run: sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev
      - name: Query dependencies
        run: |
          install.packages('remotes')
        shell: Rscript {0}

      - name: Install system dependencies
        run: |
          remotes::install_github("ropensci/opentripplanner")
        shell: Rscript {0}
      - name: Load package
        run: |
          library(opentripplanner)
        shell: Rscript {0}
